mosip/admin-services

- admin/admin-service/src/main/java/io/mosip/admin/packetstatusupdater/constant/AdminManagerProxyErrorCode.java
- admin/admin-service/src/main/java/io/mosip/admin/packetstatusupdater/service/impl/AuditManagerProxyServiceImpl.java
- admin/admin-service/src/test/java/io/mosip/admin/packetstatusupdater/AuditManagerProxyTest.java
> test case for admin proxy

- admin/admin-service/src/main/java/io/mosip/admin/packetstatusupdater/service/impl/PacketStatusUpdateServiceImpl.java
- admin/admin-service/src/main/java/io/mosip/admin/packetstatusupdater/util/AuditUtil.java
MOS-30730 fix for packet status service
> MOS-30730 changes made in packet status service

- admin/admin-service/src/main/java/io/mosip/admin/packetstatusupdater/constant/PacketStatusUpdateErrorCode.java
- admin/admin-service/src/main/java/io/mosip/admin/packetstatusupdater/service/impl/PacketStatusUpdateServiceImpl.java
- admin/admin-service/src/test/java/io/mosip/admin/packetstatusupdater/PacketStatusIntegrationTest.java
> MOSIP-179 changes made in admin services

- admin/pom.xml
updated pom with sonar rules to integrate with sonarcloud
> updated pom with sonar rules

- admin/pom.xml
> added profile for sonar

- admin/pom.xml
> updated profile for sonar

- .github/workflows/mavenpublish.yml
- .github/workflows/release_trigger.yml
- admin/pom.xml
> Sonar impl

- admin/admin-service/pom.xml
removed snapshot and updated with the release version
> removed snapshot

- admin/admin-service/src/main/java/io/mosip/admin/bulkdataupload/service/impl/BulkDataUploadServiceImpl.java
> MOSIP-9676

- admin/admin-service/src/main/java/io/mosip/admin/bulkdataupload/constant/BulkUploadErrorCode.java
- admin/admin-service/src/main/java/io/mosip/admin/bulkdataupload/contoller/BulkDataUploadController.java
- admin/admin-service/src/main/java/io/mosip/admin/bulkdataupload/service/impl/BulkDataUploadServiceImpl.java
- admin/admin-service/src/main/resources/application-local.properties
fixed bug for validation in bulkupload api
> MOSIP-9255

- admin/admin-service/src/test/java/io/mosip/admin/packetstatusupdater/PacketStatusIntegrationTest.java
this file refers to non existing method in test package
> file refers to non existing method

- admin/admin-service/src/main/java/io/mosip/admin/bulkdataupload/service/impl/BulkDataUploadServiceImpl.java
> MOSIP-10072_patch

- admin/admin-service/src/main/java/io/mosip/admin/bulkdataupload/entity/MachineHistory.java
- admin/admin-service/src/main/java/io/mosip/admin/config/Mapper.java
Added reg_working_nonworking Repo in Mapper
> MOSIP-10693

- admin/admin-service/Dockerfile
> Added Docker user

- kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/controller/DynamicFieldController.java
- kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/utils/MachineUtil.java
- kernel-masterdata-service/src/test/java/io/mosip/kernel/masterdata/test/utils/MachineUtilTest.java
- kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/constant/MasterDataErrorCode.java
- kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/controller/SyncAuthTokenController.java
- kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/controller/SyncDataController.java
- kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/dto/MachineOtpDto.java
- kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/dto/SyncUserDto.java
- kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/service/SyncUserDetailsService.java
- kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/service/helper/IdentitySchemaHelper.java
- kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/service/impl/SyncAuthTokenServiceImpl.java
- kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/service/impl/SyncMasterDataServiceImpl.java
- kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/service/impl/SyncUserDetailsServiceImpl.java
- kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/utils/SyncMasterDataServiceHelper.java
- kernel-syncdata-service/src/main/resources/application-local.properties
- kernel-syncdata-service/src/test/java/io/mosip/kernel/syncdata/test/config/TestSecurityConfig.java
- kernel-syncdata-service/src/test/java/io/mosip/kernel/syncdata/test/controller/SyncAuthTokenControllerTest.java
- kernel-syncdata-service/src/test/java/io/mosip/kernel/syncdata/test/service/SyncUserDetailsAndRolesServiceTest.java
- kernel-syncdata-service/src/test/java/io/mosip/kernel/syncdata/test/service/syncAuthServiceTest.java
- kernel-syncdata-service/src/test/resources/application.properties
1. added sendotp api and related test cases added 
2. Added Default role to dynamicfields GET api 
3. Added userdetail API based on keyindex to return encrypted data 
4. Removed usage of tpmRequired property during machine create and update
5. Corrected error message
> 1.1.4 tasks

- .github/workflows/push_trigger.yml
- .github/workflows/release_trigger.yml
fix the build issue
move the folder structure
> fix the space

- admin/admin-service/src/main/java/io/mosip/admin/bulkdataupload/entity/ZoneUserHistory.java
- admin/admin-service/src/main/java/io/mosip/admin/bulkdataupload/entity/id/ZoneUserHistoryId.java
- admin/admin-service/src/main/java/io/mosip/admin/bulkdataupload/repositories/ZoneUserHistoryRepository.java
- admin/admin-service/src/main/java/io/mosip/admin/bulkdataupload/service/impl/BulkDataUploadServiceImpl.java
- admin/admin-service/src/main/java/io/mosip/admin/config/Mapper.java
- admin/admin-service/src/main/java/io/mosip/admin/config/MapperUtils.java
- admin/admin-service/src/main/java/io/mosip/admin/config/RepositoryListItemWriter.java
Added code to update history tables simultaneously with master tables.
> MOSIP-10515

- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/constant/DeviceSpecificationErrorCode.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/constant/DeviceTypeErrorCode.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/constant/DocumentCategoryErrorCode.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/constant/DocumentTypeErrorCode.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/constant/MachineSpecificationErrorCode.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/constant/MachineTypeErrorCode.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/constant/RegistrationCenterTypeErrorCode.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/constant/TemplateFileFormatErrorCode.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/repository/DeviceRepository.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/repository/DeviceTypeRepository.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/repository/MachineSpecificationRepository.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/DeviceSpecificationServiceImpl.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/DeviceTypeServiceImpl.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/DocumentCategoryServiceImpl.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/DocumentTypeServiceImpl.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/MachineSpecificationServiceImpl.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/MachineTypeServiceImpl.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/RegistrationCenterTypeServiceImpl.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/TemplateFileFormatServiceImpl.java
- admin/kernel-masterdata-service/src/test/java/io/mosip/kernel/masterdata/test/integration/MasterdataIntegrationTest.java
- admin/kernel-masterdata-service/src/test/resources/bootstrap.properties
if one entity mapped to the another entity is should not be deactivated
> MOSIP-10386

- admin/kernel-syncdata-service/pom.xml
- admin/kernel-syncdata-service/src/main/resources/application-local.properties
- admin/kernel-syncdata-service/src/test/resources/application.properties
1. updated new properties related keymanager
2. Corrected version in pom.xml
> Corrected version in pom.xml

- admin/admin-service/src/main/java/io/mosip/admin/bulkdataupload/service/BulkDataService.java
- admin/admin-service/src/main/java/io/mosip/admin/bulkdataupload/service/impl/BulkDataUploadServiceImpl.java
- While Uploading the .csv file incase there is any extra field it should be trimmed
> MOSIP-10006

- admin/kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/SyncDataBootApplication.java
- admin/kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/websub/PartnerCACertEventSubscriber.java
Using Scheduled annotation instead of applicationreadyevent to subscribe to websub topic
> Using Scheduled annotation instead of applicationreadyevent

- .github/workflows/push_trigger.yml
- admin/admin-service/Dockerfile
- admin/kernel-masterdata-service/Dockerfile
- admin/kernel-syncdata-service/Dockerfile
Added common directory for additional dependencies/jars required. Pointed loader path to a common dir path.
> Added directory for additional dependencies/jars.

- admin/kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/repository/MachineRepository.java
- admin/kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/service/helper/ApplicationDataHelper.java
- admin/kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/service/helper/DeviceDataHelper.java
- admin/kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/service/helper/DocumentDataHelper.java
- admin/kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/service/helper/HistoryDataHelper.java
- admin/kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/service/helper/IdentitySchemaHelper.java
- admin/kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/service/helper/IndividualDataHelper.java
- admin/kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/service/helper/MachineDataHelper.java
- admin/kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/service/helper/MiscellaneousDataHelper.java
- admin/kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/service/helper/RegistrationCenterDataHelper.java
- admin/kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/service/helper/TemplateDataHelper.java
- admin/kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/service/impl/SyncAuthTokenServiceImpl.java
- admin/kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/service/impl/SyncConfigDetailsServiceImpl.java
- admin/kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/utils/SyncMasterDataServiceHelper.java
- admin/kernel-syncdata-service/src/test/java/io/mosip/kernel/syncdata/test/service/syncAuthServiceTest.java
Removed empty key maps in the sync response
Remap issues - Fixes related to machine inactive
> MOSIP-12076

- admin/kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/service/helper/IndividualDataHelper.java
Required for backward compatibility
> added gender and individualType entity data

- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/IdentitySchemaServiceImpl.java
isDelete flag by default changed to false
> isDeleted flag by default set to false

- admin/kernel-masterdata-service/pom.xml
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/constant/UISpecErrorCode.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/controller/SchemaController.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/controller/UISpecController.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/dto/IdentitySchemaDto.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/dto/getresponse/IdSchemaResponseDto.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/entity/IdentitySchema.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/entity/UISpec.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/repository/IdentitySchemaRepository.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/repository/UISpecRepository.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/IdentitySchemaService.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/UISpecService.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/IdentitySchemaServiceImpl.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/UISpecServiceImpl.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/uispec/dto/UISpecDto.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/uispec/dto/UISpecKeyValuePair.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/uispec/dto/UISpecPublishDto.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/uispec/dto/UISpecResponseDto.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/uispec/dto/UISpecTypes.java
- admin/kernel-masterdata-service/src/test/java/io/mosip/kernel/masterdata/test/config/TestSecurityConfig.java
- admin/kernel-masterdata-service/src/test/java/io/mosip/kernel/masterdata/test/controller/IdentitySchemaControllerTest.java
- admin/kernel-masterdata-service/src/test/java/io/mosip/kernel/masterdata/test/controller/UISpecControllerTest.java
- admin/kernel-masterdata-service/src/test/java/io/mosip/kernel/masterdata/test/service/SchemaServiceTest.java
- admin/kernel-masterdata-service/src/test/java/io/mosip/kernel/masterdata/test/service/UISpecServiceTest.java
Identity schema and UI spec separated.
> MOSIP -2162 Identity schema and UI Spec Separation

- admin/kernel-masterdata-service/src/test/java/io/mosip/kernel/masterdata/test/service/UISpecServiceTest.java
Test cases correction(failing due to time)
> Test cases correction(failing due to time)

- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/controller/WorkingDayController.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/RegWorkingNonWorkingService.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/RegWorkingNonWorkingServiceImpl.java
- admin/kernel-masterdata-service/src/test/java/io/mosip/kernel/masterdata/test/controller/MasterdataControllerTest.java
- admin/kernel-masterdata-service/src/test/java/io/mosip/kernel/masterdata/test/service/MasterDataServiceTest.java
created api to fetch workingdays based on langcode - 12711
> MOSIP-12711 created api to fetch workingdays based on langcode

- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/dto/response/MachineSearchDto.java
MOSIP-12796 added publickey and signingPublickey to be part of response in machine search
> MOSIP-12796 added publickey and signingPublickey to be part of response in machine search

- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/constant/MasterDataConstant.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/constant/UserDetailsErrorCode.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/controller/UserDetailsController.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/dto/UserDto.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/dto/UsersDto.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/RegistrationCenterService.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/UserDetailsService.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/ZoneUserService.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/RegistrationCenterServiceImpl.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/UISpecServiceImpl.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/UserDetailsServiceImpl.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/ZoneUserServiceImpl.java
- admin/kernel-masterdata-service/src/test/java/io/mosip/kernel/masterdata/test/integration/MasterdataIntegrationTest.java
- admin/kernel-masterdata-service/src/test/java/io/mosip/kernel/masterdata/test/service/UISpecServiceTest.java
- admin/kernel-masterdata-service/src/test/java/io/mosip/kernel/masterdata/test/service/UserDetailsServiceTest.java
- admin/kernel-masterdata-service/src/test/java/io/mosip/kernel/masterdata/test/service/ZoneServiceTest.java
Following changes have been made.
1. Added api to get all users
2. Zone validation has been added while user center mapping
> MOSIP-10811

- admin/kernel-masterdata-service/src/test/resources/application.properties
Test cases are failing due to config missing.
> Test cases failure correction

- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/dto/RegCenterPostReqDto.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/RegistrationCenterServiceImpl.java
No of Kiosk field editable during registration center creation
> MOSIP-11308

- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/constant/ZoneUserErrorCode.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/repository/ZoneUserRepository.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/ZoneUserServiceImpl.java
- admin/kernel-masterdata-service/src/test/java/io/mosip/kernel/masterdata/test/service/ZoneServiceTest.java
Added validation to restrict multiple zones mapping to a single user
> Zone user validation

- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/repository/RegExceptionalHolidayRepository.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/repository/RegWorkingNonWorkingRepo.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/RegistrationCenterServiceImpl.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/utils/RegistrationCenterServiceHelper.java
language independentReg center workingAndNonworking days and exceptional holidays made language independent
> Not considering lang from reg workingAndNonworking days

- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/constant/MasterDataConstant.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/controller/UserDetailsController.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/UserDetailsService.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/UserDetailsServiceImpl.java
api has been added to search user details
> Search api for users

- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/controller/HolidayController.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/controller/LocationController.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/controller/RegistrationCenterTypeController.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/controller/TemplateController.java
APIs created for getting missing data
> APIs created for getting missing data

- admin/kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/controller/SyncDataController.java
- admin/kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/service/SyncMasterDataService.java
- admin/kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/service/helper/IdentitySchemaHelper.java
- admin/kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/service/impl/SyncMasterDataServiceImpl.java
added 2 more params in latestIdschema api - domain , type
> added 2 more params in latestIdschema api

- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/controller/UISpecController.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/exception/ApiExceptionHandler.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/IdentitySchemaServiceImpl.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/UISpecServiceImpl.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/uispec/dto/UISpecDto.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/uispec/dto/UISpecKeyValuePair.java
- admin/kernel-masterdata-service/src/test/java/io/mosip/kernel/masterdata/test/controller/MasterdataControllerTest.java
- admin/kernel-masterdata-service/src/test/java/io/mosip/kernel/masterdata/test/integration/DeviceProviderManagementIntegrationTest.java
- admin/kernel-masterdata-service/src/test/java/io/mosip/kernel/masterdata/test/integration/DeviceRegisterIntergrationTest.java
- admin/kernel-masterdata-service/src/test/java/io/mosip/kernel/masterdata/test/integration/LocationControllerIntegrationTest.java
- admin/kernel-masterdata-service/src/test/java/io/mosip/kernel/masterdata/test/integration/LocationSearchFilterIntegrationTest.java
- admin/kernel-masterdata-service/src/test/java/io/mosip/kernel/masterdata/test/integration/MasterDataPaginationIntegrationTest.java
- admin/kernel-masterdata-service/src/test/java/io/mosip/kernel/masterdata/test/integration/ZoneIntegrationTest.java
- admin/kernel-masterdata-service/src/test/java/io/mosip/kernel/masterdata/test/service/UISpecServiceTest.java
Added PRE_REGISTRATION_ADMIN role
> Changed jsonspec string to JsonNode

- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/MachineServiceImpl.java
Removed noOfKiosks updation while machine status changes. This moved to center creation. NoOfKiosks taking as input while machine creation
> Removed noOfKiosks updation while machine status changes.

- .github/workflows/push_trigger.yml
- admin/hotlist-service/pom.xml
- admin/kernel-masterdata-service/pom.xml
- admin/kernel-syncdata-service/pom.xml
- admin/pom.xml
moved the sonar cloud analysis just after the build process to avoid failure.
> flow change for sonar cloud.

- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/MasterDataBootApplication.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/controller/PossibleValuesController.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/dto/PossibleValueDto.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/repository/DynamicFieldRepository.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/PossibleValuesService.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/PossibleValuesServiceImpl.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/TemplateServiceImpl.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/TitleServiceImpl.java
- admin/kernel-masterdata-service/src/main/resources/application-dev.properties
- admin/kernel-masterdata-service/src/main/resources/application-local.properties
- admin/kernel-masterdata-service/src/test/java/io/mosip/kernel/masterdata/test/controller/PossibleValuesControllerTest.java
- admin/kernel-masterdata-service/src/test/resources/application.properties
- admin/kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/controller/WebsubCallbackController.java
- admin/kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/websub/PartnerCACertEventSubscriber.java
- admin/kernel-syncdata-service/src/main/resources/application-dev.properties
- admin/kernel-syncdata-service/src/main/resources/application-local.properties
1. MOSIP-12774
2. Added code to download cert from datashare URL
> MOSIP-12774

- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/repository/LocationHierarchyRepository.java
> mosip-14629 query was updated

- .github/workflows/push_trigger.yml
- admin/admin-service/Dockerfile
- admin/hotlist-service/Dockerfile
- admin/kernel-masterdata-service/Dockerfile
- admin/kernel-syncdata-service/Dockerfile
> Docker lable

- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/controller/PossibleValuesController.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/PossibleValuesService.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/PossibleValuesServiceImpl.java
- admin/kernel-masterdata-service/src/test/java/io/mosip/kernel/masterdata/test/controller/PossibleValuesControllerTest.java
- admin/kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/controller/WebsubCallbackController.java
- admin/kernel-syncdata-service/src/main/resources/application-dev.properties
- admin/kernel-syncdata-service/src/main/resources/application-local.properties
- admin/kernel-syncdata-service/src/test/resources/application.properties
1. changes in possiblevalues API -- Added role and reduced to single API
2. Using latest selfToken resttemplate in websub callback controller
> Changes in possiblevalues API

- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/repository/ZoneUserHistoryRepository.java
> mosip-15095 query modified

- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/BlacklistedWordsServiceImpl.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/DocumentCategoryServiceImpl.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/DocumentTypeServiceImpl.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/DynamicFieldServiceImpl.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/ExceptionalHolidaysServiceImpl.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/GenderTypeServiceImpl.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/IdTypeServiceImpl.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/IndividualTypeServiceImpl.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/LanguageServiceImpl.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/LocationHierarchyServiceImpl.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/LocationServiceImpl.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/RegWorkingNonWorkingServiceImpl.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/TemplateServiceImpl.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/TemplateTypeServiceImpl.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/TitleServiceImpl.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/UISpecServiceImpl.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/ValidDocumentServiceImpl.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/ZoneServiceImpl.java
- admin/kernel-masterdata-service/src/test/java/io/mosip/kernel/masterdata/test/service/MasterDataServiceTest.java
- admin/kernel-masterdata-service/src/test/resources/application.properties
spring cache modification and checked the test cases.
> mosip-13761 modified and check the test cases

- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/controller/PossibleValuesController.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/repository/DynamicFieldRepository.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/repository/LocationHierarchyRepository.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/repository/LocationRepository.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/PossibleValuesService.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/PossibleValuesServiceImpl.java
- admin/kernel-masterdata-service/src/test/java/io/mosip/kernel/masterdata/test/controller/PossibleValuesControllerTest.java
Ignoring isDeleted and isActive flag when returning possible values and removed parentlangCode query param
> removed parentlangCode query param

- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/repository/DynamicFieldRepository.java
Added order by to dynamic field select query
> MOSIP-16421

- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/MachineServiceImpl.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/ValidDocumentServiceImpl.java
> mosip-16376 and mosip-16321 fixed

- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/config/OpenApiProperties.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/config/SwaggerConfig.java
- admin/kernel-masterdata-service/src/main/resources/application-local.properties
- admin/kernel-masterdata-service/src/main/resources/bootstrap.properties
- admin/kernel-masterdata-service/src/test/resources/application.properties
> swagger3.0 modified for http to https

- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/dto/RegistrationCenterTypeDto.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/validator/CenterTypeCode.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/validator/CenterTypeCodeValidator.java
we are restrict the special character on the center-type-code
> registration center type code validation added

- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/controller/RegistrationCenterTypeController.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/dto/RegistrationCenterTypePutDto.java
> modified mosip-15150

- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/DeviceServiceImpl.java
> device search updated

- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/controller/DocumentTypeController.java
Added access roles in DocumentTypeController.java.
> Added access roles in DocumentTypeController.java.

- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/dto/AuthorizedRolesDto.java
Added new value in authorised roles dto.
> Added new value in authorised roles dto.

- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/RegisteredDeviceServiceImpl.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/utils/MachineUtil.java
- admin/kernel-masterdata-service/src/test/java/io/mosip/kernel/masterdata/test/controller/MachineControllerTest.java
- admin/kernel-masterdata-service/src/test/java/io/mosip/kernel/masterdata/test/utils/MachineUtilTest.java
- admin/kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/service/helper/ClientSettingsHelper.java
- admin/kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/service/helper/KeymanagerHelper.java
- admin/kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/service/impl/SyncAuthTokenServiceImpl.java
- admin/kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/service/impl/SyncConfigDetailsServiceImpl.java
- admin/kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/service/impl/SyncMasterDataServiceImpl.java
- admin/kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/service/impl/SyncUserDetailsServiceImpl.java
- admin/kernel-syncdata-service/src/test/java/io/mosip/kernel/syncdata/test/integration/SyncClientSettingsIntegrationTest.java
- admin/kernel-syncdata-service/src/test/java/io/mosip/kernel/syncdata/test/integration/SyncDataIntegrationTest.java
- admin/kernel-syncdata-service/src/test/java/io/mosip/kernel/syncdata/test/service/SyncDataServiceTest.java
- admin/kernel-syncdata-service/src/test/java/io/mosip/kernel/syncdata/test/service/syncAuthServiceTest.java
Reverts mosip/admin-services#493
> Revert "Replaced usage of deprecated methods from cryptoUtil class"

- admin/kernel-syncdata-service/src/test/java/io/mosip/kernel/syncdata/test/SyncCacheTest.java
Reverts mosip/admin-services#514
> Revert "resolved data integrity issue"

- admin/admin-service/src/main/java/io/mosip/admin/service/impl/AdminServiceImpl.java
Reverts mosip/admin-services#566
> Revert "removed restclient for lostRid api"

- admin/hotlist-service/src/main/java/io/mosip/hotlist/controller/HotlistController.java
- admin/hotlist-service/src/main/java/io/mosip/hotlist/dto/AuthorizedRolesDto.java
- admin/hotlist-service/src/main/java/io/mosip/hotlist/interceptor/HotlistEntityInterceptor.java
- admin/hotlist-service/src/main/java/io/mosip/hotlist/security/HotlistSecurityManager.java
> [MOSIP-17828] Updated hotlist service with latest AuthN and AuthZ

- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/controller/DynamicFieldController.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/repository/DynamicFieldRepository.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/DynamicFieldService.java
- admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/DynamicFieldServiceImpl.java
- admin/kernel-masterdata-service/src/test/java/io/mosip/kernel/masterdata/test/controller/DynamicFieldControllerTest.java
Reverts mosip/admin-services#657
> Revert "MOSIP-18584"

- admin/admin-service/src/main/java/io/mosip/admin/controller/KeyManagerController.java
Reverts mosip/admin-services#685
> Revert "issue in key manager"

- admin/kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/repository/TemplateTypeRepository.java
- admin/kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/utils/SyncMasterDataServiceHelper.java
Fetching TemplateType based on Template data - to only fetch the entries related to registrationclient
> MOSIP-27529

- .github/workflows/db-test.yml
* [MOSIP-29918] added db-test.yml
* [MOSIP-29918] added db-test.yml
* [MOSIP-29918] added db-test.yml
---------
[MOSIP-29918]: https://mosip.atlassian.net/browse/MOSIP-29918?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOSIP-29918]: https://mosip.atlassian.net/browse/MOSIP-29918?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOSIP-29918]: https://mosip.atlassian.net/browse/MOSIP-29918?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOSIP-29918] added db-test.yml (#912)

- apitest/pom.xml
MOSIP-30868 | added plug-ins to point it mosiptestrunner
> MOSIP-30868

- apitest/Dockerfile
- apitest/entrypoint.sh
- apitest/pom.xml
- apitest/src/main/java/io/mosip/testrig/apirig/testscripts/PutWithPathParamsAndBody.java
Updated the maven plugin in the POM and merged the changes from the develop branch
> Updated the maven plugins

- apitest/src/main/resources/masterdata/GetApplicantType/GetApplicantType.yml
- apitest/src/main/resources/masterdata/MachineSpecification/CreateMachineSpecification.yml
MOSIP-33945 - Fixed the failure test cases
> MOSIP-33945 - Fixed the failure test cases

- apitest/src/main/java/io/mosip/testrig/apirig/testrunner/MosipTestRunner.java
- apitest/testNgXmlFiles/masterdataApi.xml
MOSIP-34117 - Fixed failure test cases in master-data
> MOSIP-34117 - Fixed master data failures

- apitest/src/main/resources/masterdata/RegistrationCenter/UpdateRegistrationCenter.yml
- apitest/testNgXmlFiles/masterdataApi.xml
MOSIP-34506 - Fixed masterdata failure test cases
> MOSIP-34506 - Fixed masterdata failure test cases

- apitest/src/main/resources/masterdata/FetchRegCent/FetchRegCent.yml
- apitest/src/main/resources/masterdata/FetchRegCentHistory/FetchRegCentHistory.yml
- apitest/src/main/resources/masterdata/FetchValidDocuments/FetchValidDocuments.yml
- apitest/src/main/resources/masterdata/RegCenterSearch/RegCenterSearch.yml
- apitest/src/main/resources/masterdata/SearchMachineSpec/SearchMachineSpec.yml
- apitest/src/main/resources/masterdata/UserCenterMapping/UpdateUserCenterMapping.yml
- apitest/src/main/resources/masterdata/UserCenterMapping/UserCenterMapping.yml
MOSIP-35082 - Fixed failure test cases
> MOSIP-35082 - Fixed failure test cases

- apitest/pom.xml
MOSIP-32453: resolved build issue
> MOSIP-32453: resolved build issue

- apitest/src/main/resources/config/Kernel.properties
- apitest/src/main/resources/masterdata/Device/CreateDevice.yml
- apitest/src/main/resources/masterdata/Device/UpdateDevice.yml
- apitest/src/main/resources/masterdata/GetRegistrationMachineUserMappingHistory/Getregistrationmachineusermappinghistory.yml
- apitest/testNgXmlFiles/masterdataApi.xml
MOSIP-35897 - Fixed automation failures
> MOSIP-35897 - Fixed automation failures

- api-test/testNgXmlFiles/masterdataApi.xml
MOSIP-36093 - Pushed apitest to release branch
> MOSIP-36093 - Pushed apitest to release branch

- api-test/pom.xml
MOSIP-36093 - Updating the apitest commons version
> MOSIP-36093 - Updating the apitest commons version

- api-test/README.md
MOSIP-34532 - Updated the ReadMe file
> MOSIP-34532 - Updated the ReadMe file

- api-test/src/main/resources/masterdata/SearchMachineSpec/SearchMachineSpec.yml
- api-test/src/main/resources/masterdata/SearchMachineSpec/searchMachineSpecResult.hbs
MOSIP-37943 - Removed the template field for search machine spec with model
> MOSIP-37943 - Removed the template field for search machine spec with model

- api-test/pom.xml
MOSIP-36480 - updated the apitest commons version
> MOSIP-36480 - updated the apitest commons version

- api-test/pom.xml
MOSIP-36480 - updated the groupId
> MOSIP-36480 - updated the groupId

- api-test/pom.xml
- api-test/src/main/resources/masterdata/FetchRegCent/FetchRegCent.yml
MOSIP-40967 - Added the not automated testcases from mastersheet
> MOSIP-40967 - Added the not automated testcases from mastersheet

- admin/kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/utils/SyncMasterDataServiceHelper.java
[MOSIP-43188]
[MOSIP-43188]: https://mosip.atlassian.net/browse/MOSIP-43188?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOSIP-43188 fixed Longitude null issue
